[package]
name = "rollgui"
version = "0.1.0"
authors = ["Bastien Sevajol <sevajol.bastien@gmail.com>"]
edition = "2018"

[dependencies]
doryen-rs="1.2.*"
doryen-ui = { git = "https://github.com/jice-nospam/doryen-ui.git", rev = "0ffe6d1a74d32fd720615b78aed466ad37adfc46" }
websocket = "0.24.0"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
pickledb = "0.4.0"
reqwest = { version = "0.10.1", features = ["blocking", "json"] }
colors-transform = "0.2.11"
url = "2.1.1"
