[package]
name = "rollgui"
version = "0.2.0"
authors = ["Bastien Sevajol <bastien.sevajol@algoo.fr>"]
edition = "2018"

[dependencies]
coffee = { git = "https://github.com/buxx/coffee.git", rev = "a2b1a0966c738757493ac5f412e67f9745561e79", features = ["opengl"] }
rand = "0.6"
pickledb = "0.4.0"
websocket = "0.24.0"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
reqwest = { version = "0.10.1", features = ["blocking", "json"] }
url = "2.1.1"
