[package]
name = "rollgui"
version = "0.1.0"
authors = ["Bastien Sevajol <sevajol.bastien@gmail.com>"]
edition = "2018"

[dependencies]
doryen-fov = "0.1.1"
doryen-rs = "1.2.1"
websocket = "0.24.0"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
