[package]
name = "rollgui"
version = "0.1.0"
authors = ["Bastien Sevajol <sevajol.bastien@gmail.com>"]
edition = "2018"

[dependencies]
doryen-rs = "1.2.2"
doryen-ui = { git = "https://github.com/jice-nospam/doryen-ui.git", rev = "101edb85669df791b484aa4d802b32665352734c" }
