use crate::gui::lang::model::{Description, RequestClicks};
use crate::server;

#[derive(Debug, Clone)]
pub enum MainMessage {
    ToStartup,
    ToExit,
    ToWorld,
    ExitRequested,
    StartupToZone {
        disable_version_check: bool,
    },
    DescriptionToZone {
        request_clicks: Option<RequestClicks>,
    },
    NewCharacterId {
        character_id: String,
    },
    CreateAccount {
        address: server::ServerAddress,
    },
    AccountCreated,
    ToDescriptionWithDescription {
        description: Description,
        back_url: Option<String>,
        client: server::client::Client,
    },
    ToDescriptionWithUrl {
        url: String,
        back_url: Option<String>,
    },
    EnterServer {
        credentials: (String, String),
        character_id: Option<String>,
    },
}

#[derive(Debug, Clone)]
pub enum Message {
    ConfirmButtonPressed,
    CancelButtonPressed,
    DownloadButtonPressed,
    ContinueButtonPressed,
    PasswordLostButtonPressed,
    CreateAccountButtonPressed,
    ResetProgressBar,
    LocalServerPressed,
    S2BuxFrServerPressed,
    TextInputSelected(i32),
    LoginInputSelected(i32),
    PasswordInputSelected(i32),
    SubmitButtonPressed,
    CheckBoxChecked(i32),
    CheckBoxUnchecked(i32),
    LinkButtonPressed(i32),
    WebBrowserLinkButtonPressed(String),
    LinkButtonReleased(String),
    GroupLinkButtonPressed(i32),
    GroupLinkButtonReleased(String),
    ChoicePressed(i32, i32),
    SearchByStrInputPressed(i32),
    SearchByStrButtonPressed(i32, i32),
    SearchByStrButtonReleased(i32, i32),
    GoBackFromGroupButtonPressed,
    GoBackZoneButtonPressed,
    GoBackButtonPressed(String),
    GoBackWithCharacterButtonPressed(String),
    GoBackActionButtonPressed,
    GoBackInventoryButtonPressed,
    GoBackWithBuildButtonPressed(i32),
    GoBackWithAffinityButtonPressed(i32),
    WorldMenuButtonPressed,
    CardMenuButtonPressed,
    EventsMenuButtonPressed,
    BusinessMenuButtonPressed,
    AffinitiesMenuButtonPressed,
    ZoneMenuButtonPressed,
    ZoneMessagesMenuButtonPressed,
    ConversationsMenuButtonPressed,
    InventoryMenuButtonPressed,
    ActionMenuButtonPressed,
    BuildMenuButtonPressed,
    ServerInfosMenuButtonPressed,
    OpenAccountButtonPressed,
    ExitMenuButtonPressed,
    ToStartupPressed,
    AroundItemsButtonPressed,
    AroundBuildButtonPressed,
    AroundCharactersButtonPressed,
    SubmitChatButtonPressed,
    PreviousChatButtonPressed,
    NextChatButtonPressed,
    DismissRequestClicks,
    DismissChat,
    RequestChat(Option<i32>),
    QuickActionPressed(String),
}
